
MIPSsim : main.cc memory.cc instructions.cc utility.cc memory.h instructions.h utility.h memory.h type.h instr_defs.h
	g++ -g main.cc memory.cc instructions.cc utility.cc -Wall -o MIPSsim

.PHONY : clean

clean :
	rm MIPSsim